# Generated by Django 5.1.2 on 2025-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='slogan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
