# Generated by Django 5.1.2 on 2024-11-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripPlanner', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='review',
            name='place',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
