# Generated by Django 5.1.2 on 2025-02-06 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0002_cityimage_author_countryimage_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='countryimage',
            name='country',
        ),
        migrations.RemoveField(
            model_name='districtimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='districtimage',
            name='district',
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='place',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='regionimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='regionimage',
            name='region',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.RemoveField(
            model_name='tripimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tripimage',
            name='trip',
        ),
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(max_length=15)),
                ('model_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='<django.db.models.fields.TextField>_images/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CityImage',
        ),
        migrations.DeleteModel(
            name='CountryImage',
        ),
        migrations.DeleteModel(
            name='DistrictImage',
        ),
        migrations.DeleteModel(
            name='PlaceImage',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='RegionImage',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
