# Generated by Django 5.1.2 on 2025-02-06 22:46

import apps.ImageApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0003_remove_countryimage_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='image',
            field=models.ImageField(upload_to=apps.ImageApp.models.image_upload_path),
        ),
    ]
