# Generated by Django 5.1.2 on 2025-01-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceApp', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(related_name='places', to='PlaceApp.category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='fsq_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
