# Generated by Django 5.1.2 on 2025-01-03 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceApp', '0004_remove_place_category_place_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='fsq_id',
        ),
        migrations.AddField(
            model_name='place',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
