# Generated by Django 5.1.2 on 2025-01-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceApp', '0005_remove_place_fsq_id_place_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
