# Generated by Django 5.1.2 on 2024-11-01 06:58

from django.db import migrations




class Migration(migrations.Migration):
    dependencies = [
        ('Db_api', '0002_country_user_followers_alter_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
