# Generated by Django 5.1.2 on 2024-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Db_api', '0004_category_place_fsq_id_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='coordinates',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
