# Generated by Django 5.1.2 on 2024-11-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Db_api', '0005_alter_city_coordinates_alter_place_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(default='Не указан', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='avg_rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
