# Generated by Django 5.1.2 on 2024-11-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Db_api', '0008_alter_user_photo_favoriteplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='photos',
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Db_api.place')),
            ],
        ),
    ]
