# Generated by Django 5.1.2 on 2024-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Db_api', '0009_remove_place_photos_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
