# Generated by Django 5.1.2 on 2024-11-11 11:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('Db_api', '0012_remove_city_country_alter_favoriteplace_user_and_more'),
    ]

    migrations.AddField(
    model_name='review',
    name='author',
    field=models.ForeignKey(on_delete=models.CASCADE, related_name='user_reviews', to='your_app.User'),
    preserve_default=False,
    ),

    operations = [
    ]
