# Generated by Django 5.1.2 on 2024-11-18 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Db_api', '0013_auto_20241111_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewphotos',
            name='review',
        ),
        migrations.RemoveField(
            model_name='city',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='district',
            name='image',
        ),
        migrations.RemoveField(
            model_name='region',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photos',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='city_images/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityimage_set', to='Db_api.city')),
            ],
        ),
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country_images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countryimage_set', to='Db_api.country')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='district_images/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districtimage_set', to='Db_api.district')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_photos/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimage_set', to='Db_api.post')),
            ],
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='region_images/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regionimage_set', to='Db_api.region')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_photos/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewimage_set', to='Db_api.review')),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_images/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripimage_set', to='Db_api.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='PostPhoto',
        ),
        migrations.DeleteModel(
            name='ReviewPhotos',
        ),
    ]
