# Generated by Django 5.1.2 on 2024-12-29 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceApp', '0003_alter_category_icon'),
        ('TripApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='trippers',
            field=models.ManyToManyField(related_name='trippers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cities',
            field=models.ManyToManyField(related_name='trip_cities', to='PlaceApp.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(related_name='trip_places', to='PlaceApp.place'),
        ),
    ]
