# Generated by Django 5.1.2 on 2024-12-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceApp', '0003_alter_category_icon'),
        ('ReviewApp', '0002_alter_review_text'),
        ('TripApp', '0002_remove_trip_country_remove_trip_user_trip_trippers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='places',
        ),
        migrations.CreateModel(
            name='SubTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtrips', to='TripApp.trip')),
            ],
            options={
                'unique_together': {('trip', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SubtripReviewPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtrip_review_places', to='PlaceApp.place')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ReviewApp.review')),
                ('subtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtrip_places', to='TripApp.subtrip')),
            ],
            options={
                'unique_together': {('subtrip', 'place', 'review')},
            },
        ),
    ]
