# Generated by Django 5.1.2 on 2025-01-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceApp', '0005_remove_place_fsq_id_place_services'),
        ('TripApp', '0003_remove_trip_places_subtrip_subtripreviewplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtripPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtrip_review_places', to='PlaceApp.place')),
                ('subtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtrip_places', to='TripApp.subtrip')),
            ],
            options={
                'unique_together': {('subtrip', 'place')},
            },
        ),
        migrations.DeleteModel(
            name='SubtripReviewPlace',
        ),
    ]
