# Generated by Django 5.1.2 on 2025-01-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0004_subtripplace_delete_subtripreviewplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='temp_image',
            field=models.ImageField(default='trip_photos/trip_base.png', upload_to='trip_photos/'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to=settings.AUTH_USER_MODEL)),
                ('subtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtrip_notes', to='TripApp.subtrip')),
            ],
        ),
    ]
