# Generated by Django 5.1.2 on 2025-01-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0005_trip_temp_image_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cities',
        ),
        migrations.AddField(
            model_name='trip',
            name='cities',
            field=models.CharField(default='Не указан', max_length=150),
        ),
    ]
