# Generated by Django 5.1.2 on 2025-01-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0006_remove_trip_cities_trip_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tittle',
            new_name='title',
        ),
    ]
