# Generated by Django 5.1.2 on 2025-01-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0011_alter_subtripplace_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtripplace',
            name='category_icon',
            field=models.ImageField(default='subtripplace/default.svg', upload_to='subtripplace/'),
        ),
    ]
