FOURSQUARE_API_KEY = 'fsq34Zy+vMIVStXkOn52f0vpDs+Om19xxkMKaXfrqRJF0mg='
DATABASE_NAME = 'ToTrip_BD'
DATABASE_USERNAME = 'postgres'
DATABASE_PASSWORD = '2396ToTripUlitki'
DATABASE_HOST = 'localhost'
DATABASE_PORT = '5432'

